connection_threshold: 0.0325
fixed_frame: odom
kalman_on: 1
kalman_p: 4.0
kalman_q: 0.002
kalman_r: 10.0
leg_pair_separation: 0.4
leg_reliability_limit: 0.0
max_meas_jump: 1.45
max_second_leg_age: 5.0
max_track_jump: 2.05
min_points_per_group: 1
no_observation_timeout: 0.55
publish_leg_markers: true
publish_legs: true
publish_people: true
publish_people_markers: true

