# Docker file for MARRtino software
# ROS Melodic, navigation, perception & additional packages
# Version base

# docker build -t marrtino:base -f Dockerfile.base .

FROM marrtino:system

USER robot

# marrtino_apps

RUN cd $HOME/src && \
    git clone --depth 1 https://bitbucket.org/iocchi/marrtino_apps.git

WORKDIR /home/robot

CMD [ "/bin/bash", "-ci", "/home/robot/src/marrtino_apps/bringup/1-bringup.bash", "-docker" ]


